### ISSUE TITLE
Error on adding new child entries

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBCMOrganizer#5] opened 2020-05-25 20:16 UTC
sometimes when copying a child entry from a BCM entry and then pasting it into another BCM entry

YaBCMwill yields errors like this : 
![image](https://user-images.githubusercontent.com/47185022/82841153-ae73b100-9edd-11ea-88ca-7175ed7e6fee.png)

the "KeyError" number is variant, but the result is always the same:
it appends the child entry with no names, and the BCM doesn't save correctly 
![image](https://user-images.githubusercontent.com/47185022/82841187-d105ca00-9edd-11ea-9b32-b3303b8b4c36.png)

**Comment by KyonkoYuuki** [comment] 2020-05-26 01:41
Need a specific example and steps taken to get that error, especially if you say it only happens sometimes.

Also mostly because I can't replicate it.

**Comment by KyonkoYuuki** [comment] 2020-05-26 02:10
Probably related:
https://github.com/KyonkoYuuki/YaBCMOrganizer/issues/7

**Comment by UnleashedGH** [comment] 2020-05-26 16:35
> Need a specific example and steps taken to get that error, especially if you say it only happens sometimes.
> 
> Also mostly because I can't replicate it.

the error occurs on any moveset BCM and any skill BCM that has complex hierarchy.
i used GOK_PLAYER.bcm here.
not quite sure what causes the error, #7 is most likely the cause

**Comment by KyonkoYuuki** [comment] 2020-05-26 20:59
the error is caused by https://github.com/KyonkoYuuki/YaBCMOrganizer/issues/7 because the child/sibling links are broken in some BCM's

**Comment by KyonkoYuuki** [comment] 2020-05-27 02:55
Going to close this in favor of fixing it as part of https://github.com/KyonkoYuuki/YaBCMOrganizer/issues/7

**Closed as completed by KyonkoYuuki** 2020-05-27 02:55 UTC
